#!/bin/sh
# Intended for use with m-lab/git-hooks.
# Clone or use submodule, and link .git/hooks to git-hooks,
#  e.g.
#    mv .git/hooks .git/hooks.orig
#    ln -s ../../git-hooks .git/hooks
#
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

set -x
set -u
# travis lint -x # Now done by git-hooks/pre-commit

golint ./...
go vet ./...
