apiVersion: v1
kind: Service
metadata:
  name: etl-gardener-service
  namespace: default
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: etl-gardener-universal
  sessionAffinity: None
  type: ClusterIP
