apiVersion: v1
kind: Service
metadata:
  name: etl-gardener-status
  namespace: default
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    run: etl-gardener-universal
  sessionAffinity: None
  type: LoadBalancer
