apiVersion: v1
kind: Service
metadata:
  name: etl-gardener-service
  namespace: default
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
    #cloud.google.com/neg: '{"exposed_ports":{"8080":{}}}'
    # INGRESS seems to persist even after commenting this out!
    # kubernetes.io/ingress.regional-static-ip-name: mlab-etl-gardener
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: etl-gardener-universal
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 10.100.1.2  # etl-gardener us-east1/default/default-gardener subnet - this hard codes the service address.
